### ISSUE TITLE
[SubverseV2] Implement TCP Support

### ISSUE THREAD

**Issue by SubverseIM** [SubverseIM/Subverse.NET#20]
For the SubverseV2 protocol, TCP support should be added to the protocol stack. 

This includes adapting the designs of `QuicEntityConnection` and `QuicHubConnection`, as well as `QuicListenerService` to function in a similar capacity over TCP/IP.

**Comment by IsaMorphic** [comment]
This has the potential to be a good enhancement, as it could increase overall compatibility. However, it does raise another concern, which I will open an issue for here, regarding how we handle proxied connections, or whether this scenario should be supported at all.

~~TODO: Reference that issue~~
